### ISSUE TITLE
Why paseo-asset-hub.json is 275 Mb? 

### ISSUE THREAD

**Issue by BulatSaif** [paseo-network/paseo-chain-specs#8]
The average chainspec size is 1-5 MB, but I see that the `paseo-asset-hub.json` is  275Mb
![image](https://github.com/user-attachments/assets/ea1c72d6-d65f-4f63-90f9-034edaaa21de)

Before moving the chainspec to this repository, its size was 1.97 MB: https://github.com/paseo-network/runtimes/blob/592cafbd1a8efc6516bc3d9f9166b02403f56440/chain-specs/asset-hub-paseo.raw.json

**Comment by BulatSaif** [comment]
@al3mart, can you please check if you added the correct file to this repo?

**Comment by hbulgarini** [comment]
Hello! The size is correct since we had to restore the AH system chain due to a failed runtime upgrade that we solved it almost instantaneity. But the consequence is that the chain spec size is quite big now as it contains the state from the chain prior to the failed runtime upgrade.
